services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    networks:
      - sgm_network
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - sgm_network
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
networks:
  sgm_network:
    driver: bridge
